services:
  db:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    expose:
      - "5432"
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - type: bind
        source: ./
        target: /rails
    ports:
      - "3000:3000"
    depends_on:
      - db
